import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import MarketingGrid from "components/grid_with_offset_icons";
import Footer from "components/footer";
import HeroHeader from "components/heroheader";
import AlertTop from "components/alertTop";
import NavBar from "components/navbar";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Vulcan Labs</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/cropped-vl_stamp_white_with_black_hammer_bordered512-32x32.png" sizes="32x32" />
        <link rel="icon" href="/cropped-vl_stamp_white_with_black_hammer_bordered512-192x192.png" sizes="192x192" />
      </Head>

      <AlertTop
        buttonText="Learn more"
        href="/"
        text={{
          sm: "We announced a new product!",
          md: "Big news! We're excited to announce a brand new product."
        }}
      />

      <NavBar navigation={[
        { name: 'Home', href: '#', current: true },
        { name: 'Expertise', href: '#', current: false },
        { name: 'Services', href: '#', current: false },
        { name: 'Success Stories', href: '#', current: false },
        { name: 'About', href: '#', current: false },
        { name: 'Careers', href: '#', current: false },
      ]} />

      <HeroHeader
        headline="Let's build something amazing!"
        pitchtext="Leading edge software product development services through all stages of production."
      />


      

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-800 to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[4rem]">Hello Vulcan Team!</h1>
          <h1 className="text-2xl font-extrabold tracking-tight text-white ">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App is awesome :)
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>

      <MarketingGrid />

      <Footer />
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData?.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
