import React, { type ReactNode } from "react";
import Head from "next/head";
import AlertTop from "./alertTop";
import NavBar from "./navbar";
import { Container } from "./container";

export function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Vulcan Labs</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link
          rel="icon"
          href="/cropped-vl_stamp_white_with_black_hammer_bordered512-32x32.png"
          sizes="32x32"
        />
        <link
          rel="icon"
          href="/cropped-vl_stamp_white_with_black_hammer_bordered512-192x192.png"
          sizes="192x192"
        />
      </Head>
      <main>
        <AlertTop
          buttonText="Learn more"
          href="/"
          text={{
            sm: "We announced a new product!",
            md: "Big news! We're excited to announce a brand new product.",
          }}
        />

        <NavBar
          navigation={[
            { name: "Home", href: "#" },
            { name: "Expertise", href: "#" },
            {
              name: "Services",
              href: "#",
              subnav: [
                { name: "Custom Development", href: "/services/customdev" },
                {
                  name: "Specialist IT Resourcing",
                  href: "/services/itresourcing",
                },
                { name: "Dedicated Team", href: "/services/dedicatedteam" },
              ],
            },
            { name: "Success Stories", href: "#" },
            { name: "About", href: "#" },
            { name: "Careers", href: "#" },
          ]}
        />

        <Container>{children}</Container>
      </main>
    </>
  );
}
